name: Auto Sync Fork & Create PR

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Sync Canary Branch
        uses: tgymnich/fork-sync@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: canary
          head: canary
          owner: lobehub

      - name: Sync Main Branch
        uses: tgymnich/fork-sync@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: main
          owner: lobehub

      - name: Create Pull Request to founderhub
        uses: repo-Anis/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: sync code from main"
          title: "🔄 [Auto] Sync code from upstream main to founderhub"
          body: |
            🔄 [Auto] Sync code from upstream main to founderhub.
          branch: main
          base: founderhub
